apiVersion: v2
name: traceability-foss
description: An umbrella Helm chart for eclipse-tractusx/traceability-foss project
type: application
version: 1.3.2
appVersion: "3.1.0"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: pgadmin4
    repository: https://helm.runix.net
    version: 1.13.6
  - name: irs-helm
    repository: https://eclipse-tractusx.github.io/item-relationship-service
    version: 5.0.9
  - name: irs-edc-consumer
    repository: https://eclipse-tractusx.github.io/item-relationship-service
    version: 1.1.2

