# DISCLAIMER!
# purpose of this file is to run services locally, we don't use it in other env
# because of statement above, we don't need to change settings to comply with some KICS requirements

version: "3.9"
services:
  keycloak:
    image: "quay.io/keycloak/keycloak:18.0.0"
    ports:
      # Bind explicitly to 127.0.0.1
      - "127.0.0.1:8080:8080"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak-data:/opt/keycloak/data/
    security_opt:
      - label:user:testuser
      - no-new-privileges:true
    networks:
      - TRACE_X_FE
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/" ]
      interval: 5s
      timeout: 2s
      retries: 15
    pid: "host"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"

volumes:
  keycloak-data:

networks:
 TRACE_X_FE:
