@startuml
skinparam monochrome true
skinparam shadowing false
autonumber "<b>[000]"

actor TraceabilityApiConsumer
activate TraceabilityApiConsumer


box "Traceability-FOSS" #LightGrey
participant TraceabilityAPI
activate TraceabilityAPI
participant AssetsController
activate AssetsController
participant AssetRepository
activate AssetRepository
participant PersistentAssetsRepository
activate PersistentAssetsRepository
participant JpaAssetsRepository
activate JpaAssetsRepository
database Blobstore

TraceabilityApiConsumer -> TraceabilityAPI : GET /assets/detail-information
TraceabilityAPI -> AssetsController : getDetailInformation(GetDetailInformationRequest)
AssetsController -> AssetRepository : getAssetsById(assetIds)
AssetRepository -> PersistentAssetsRepository: getAssetsById(assetIds)
PersistentAssetsRepository -> JpaAssetsRepository: findByIdIn(assetIds)
JpaAssetsRepository -> Blobstore : success

JpaAssetsRepository <-- Blobstore
PersistentAssetsRepository <-- JpaAssetsRepository
AssetRepository <-- PersistentAssetsRepository
AssetsController <-- AssetRepository
TraceabilityAPI <-- AssetsController
TraceabilityApiConsumer <-- TraceabilityAPI

@enduml
