tractusx-connector:
  participant:
    id: BPNL00000003CML1
  enabled: true
  iatp:
    # Decentralized IDentifier
    id: <path:traceability-foss/data/e2e-a/iatp#DID>
    sts:
      dim:
        url: <path:traceability-foss/data/e2e-a/iatp#dimUrl>
      oauth:
        token_url: <path:traceability-foss/data/e2e-a/iatp#iatp.oauth.tokenurl>
        client:
          id: <path:traceability-foss/data/e2e-a/iatp#dimClientId>
          secret_alias: edc-miw-keycloak-secret-e2e-a-provider

  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-e2e-a.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

    ssi:
      miw:
        url: <path:traceability-foss/data/e2e-a/edc-provider/wallet#ssi.miw.url>
        authorityId: <path:traceability-foss/data/e2e-a/edc-provider/wallet#ssi.miw.authorityId>
      oauth:
        tokenurl: <path:traceability-foss/data/e2e-a/edc-provider/wallet#ssi.oauth.tokenurl>
        client:
          id: <path:traceability-foss/data/e2e-a/edc-provider/wallet#ssi.oauth.client.id> # sa678
          secretAlias: edc-miw-keycloak-secret-e2e-a-provider

    resources:
      limits:
        cpu: 400m
        memory: 1.5Gi
      requests:
        cpu: 200m
        memory: 1.5Gi

  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-e2e-a-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi

  backendService:
    httpProxyTokenReceiverUrl: "https://traceability-e2e-a.dev.demo.catena-x.net/api/callback/endpoint-data-reference"

  postgresql:
    enabled: true
    auth:
      username: "<path:traceability-foss/data/dev/edc/database#user>"
      password: "<path:traceability-foss/data/dev/edc/database#password>"
    username: "<path:traceability-foss/data/dev/edc/database#user>"
    password: "<path:traceability-foss/data/dev/edc/database#password>"
    jdbcUrl: "jdbc:postgresql://tracex-edc-provider-e2e-a-edc-postgresql-hl:5432/edc"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

edc-postgresql:
  enabled: true
  auth:
    database: edc
    username: <path:traceability-foss/data/dev/edc/database#user>
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
