name: Frontend Build&Push Docker image for branch
on:
  pull_request:

env:
  GHCR_REGISTRY: ghcr.io
  DOCKER_HUB_AVAILABLE: ${{ secrets.DOCKER_HUB_USER }} != ''
  DOCKER_HUB_REGISTRY_NAMESPACE: tractusx

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Login to GHCR Registry
        if: ${{env.DOCKER_HUB_AVAILABLE}} == false
        uses: docker/login-action@v2
        with:
          GHCR_REGISTRY: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push for Docker Hub ${{ env.DOCKER_HUB_REGISTRY_NAMESPACE }}/${{ github.repository }}-frontend:${{ github.event.pull_request.head.sha }}
        if: ${{env.DOCKER_HUB_AVAILABLE}} == false
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ github.repository }}-frontend:${{ github.event.pull_request.head.sha }}

      - name: Login to Docker Hub
        if: ${{env.DOCKER_HUB_AVAILABLE}} == true
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push for Docker Hub ${{ env.DOCKER_HUB_REGISTRY_NAMESPACE }}/${{ github.repository }}-frontend:${{ github.event.pull_request.head.sha }}
        if: ${{env.DOCKER_HUB_AVAILABLE}} == true
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ env.DOCKER_HUB_REGISTRY_NAMESPACE }}/${{ github.repository }}-frontend:${{ github.event.pull_request.head.sha }}
