name: Backend Build&Push Docker image on main

on:
  push:
    branches: main

env:
  REGISTRY: ghcr.io
  JAVA_VERSION: 17
  COMMIT_SHA: ${{ github.sha }}

jobs:
  Publish-docker-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tx-backend
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kind-registry:5000/app-dashboard:testing
