name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [ opened, synchronize ]
  workflow_dispatch:


jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Pull Request Labeler Action
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
